"""Add cascade delete to user, website, logs

Revision ID: 6d621c72d10b
Revises: a125e40106bf
Create Date: 2025-09-01 03:10:21.015664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d621c72d10b'
down_revision = 'a125e40106bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('status_log_website_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'website', ['website_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('status_log_website_id_fkey'), 'website', ['website_id'], ['id'])

    # ### end Alembic commands ###
